### ISSUE TITLE
Dynamic Messages?

### ISSUE THREAD

**Issue by riztaha** [quelchx/vue-writer#5]
**Is your feature request related to a problem? Please describe.**
I cannot have the message in the array dynamic.

**Describe the solution you'd like**
I had a computed property called message, which based on a boolean will display a different message. This does not work as an array I guess.

`const message = computed(() => { return boolean ? 'Display This if it is true' : 'Display 2nd message if it is false'; });`

**Comment by quelchx** [comment]
Have you tried 
```const message = computed(() => { return boolean ? ['Display This if it is true'] : ['Display 2nd message if it is false'] });```

It's been a while since I looked at the Vue documentation but I'm not really sure how to address this issue.

The value that is being passed has to be within an array. I can look into this in time.

**Comment by riztaha** [comment]
Yes, I tried that, it didn't work. I've tried:

```
<vue-writer
          :array="[message]"
        />

const message = computed(() => { return boolean ? 'Display This if it is true' : 'Display 2nd message if it is false'; });
```


and

```
<vue-writer
          :array="message"
        />

const message = computed(() => { return boolean ? ['Display This if it is true'] : ['Display 2nd message if it is false']; });
```


What worked was adding multiple v-ifs for each condition and not using a computed property, likeso:


```
<vue-writer
v-if='boolean'
          :array="message"
        />

<vue-writer
v-if='!boolean'
          :array="message"
        />
```

**Comment by riztaha** [comment]
What ends up happening when trying to use computed dynamic value, it seems like it only computes it onces. When the condition changes on the boolean, it doesn't recompute it and change the message.

**Comment by quelchx** [comment]
Interesting.

As I mentioned before I'm not really sure if there is any enhancement I can really add to solve this edge case issue with this package. Since this package takes an array and not a string, having just a single string value feature added as a prop and everything else working in tandem has caused issues on my end before -- hence why this package has to take in an array.

I understand your issue -- but I'm not sure what I can really do to add something to solve this specific issue you're having. 

Reading Vue's documentation in regards to the computed hook -- have you tried using the watch hook instead?

It's been a while since I have read into Vue's documentation + worked with Vue applications, so I don't want to be suggesting things for you to do because I wouldn't claim myself to be an expert with Vue.
