### ISSUE TITLE
Caret not displaying

### ISSUE THREAD

**Issue by riztaha** [quelchx/vue-writer#6]
Caret/cursor is not displaying. Using Vue3 Typescript.
The default caret does not display. When adding the caret prop, I get an error

![image](https://user-images.githubusercontent.com/59785428/157115950-5dfa8756-4d27-41bf-bdb3-96972584f751.png)

**Comment by quelchx** [comment]
That might be because the cursor is technically the default prop that is being passed. 
The only other caret that can be passed as a prop is 'underscore' which should override the default prop which is 'cursor'.

In the snippet above I would suggest not passing the `:caret` as a prop at all if you intend to use `cursor` since as mentioned its default. 

Refer to the documentation within the Github repository for a little more information in regards to that specific prop https://github.com/quelchx/vue-writer#caret

**Comment by riztaha** [comment]
Leaving it blank, the caret doesn't display either.

![image](https://user-images.githubusercontent.com/59785428/157119508-a24cb8b8-a100-4c4d-963b-8d18b7a83c9f.png)
![image](https://user-images.githubusercontent.com/59785428/157119447-2f9536ee-8560-4712-aad0-19ee9b28cda9.png)

**Comment by quelchx** [comment]
Oh sorry -- the cursor was removed by request in a previous issue. I left the styling inside the documentation and also noted this in the documentation. 

Should of mentioned this in my first comment.

**Comment by riztaha** [comment]
No worries, I manually added a caret by embedding CSS styling on my page to display it:

```
<style lang="scss">
.cursor {
  animation: typing 2.5s steps(20, end), blink-caret .75s step-end infinite;
  @apply border-r-4 border-primary;
}
/* The typing effect */
@keyframes typing {
  from { width: 0 }
  to { width: 100% }
}
/* The typewriter cursor effect */
@keyframes blink-caret {
  from, to { border-color: transparent }
  50% { border-color: black; font-size: 80%; }
}
</style>
```
